python-version = "3.12.0"
replace-imports-with-any = [
    "nemo_automodel.*",
    "pynvml.*",
    "hydra._internal.*",
    "hydra.core.override_parser.*",
    "datasets.*",
    "transformers.*",
    "vllm.*",
    "math_verify.*",
    "sympy.*",
    "torchdata.*",
    "nemo.*",
    "megatron.*",
    "ray.*",
    "numpy.*",
    "sphinx.*",
    "docutils.*",
]
project-includes = [
    # TODO: enable these once we have 100 correctness
    #"nemo_rl/**/*.py",
    #"examples/**/*.py",
    #"docs/*.py",
    #"tools/**/*.py",
    
    # Generate the list of errors per file
    # uv run --group dev pyrefly check $(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py') --output-format json | jq -r --slurpfile all_files <(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py' | jq -R -s 'split("\n")[:-1]') --arg pwd "$(pwd)/" '(.errors | group_by(.path) | map({(.[0].path | sub($pwd; "")): length}) | add // {}) as $error_counts | $all_files[0][] | . as $file | "\($error_counts[$file] // 0)\t\($file)"' | sort -n

    # Generate list of files with 0 errors
    # uv run --group dev pyrefly check $(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py') --output-format json | jq -r --slurpfile all_files <(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py' | jq -R -s 'split("\n")[:-1]') --arg pwd "$(pwd)/" '(.errors | group_by(.path) | map({(.[0].path | sub($pwd; "")): length}) | add // {}) as $error_counts | $all_files[0][] | . as $file | if ($error_counts[$file] // 0) == 0 then $file else empty end'
    # uv run --group dev pyrefly check $(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py') --output-format json | jq -r --slurpfile all_files <(git ls-files 'nemo_rl/**/*.py' 'examples/**/*.py' 'docs/*.py' 'tools/**/*.py' | jq -R -s 'split("\n")[:-1]') --arg pwd "$(pwd)/" '(.errors | group_by(.path) | map({(.[0].path | sub($pwd; "")): length}) | add // {}) as $error_counts | $all_files[0][] | . as $file | if ($error_counts[$file] // 0) == 0 then "    \"\($file)\"," else empty end'
    "docs/conf.py",
    "docs/helpers.py",
    "examples/converters/convert_dcp_to_hf.py",
    "examples/converters/convert_megatron_to_hf.py",
    "nemo_rl/algorithms/__init__.py",
    "nemo_rl/algorithms/interfaces.py",
    "nemo_rl/algorithms/utils.py",
    "nemo_rl/data/__init__.py",
    "nemo_rl/data/chat_templates.py",
    "nemo_rl/data/collate_fn.py",
    "nemo_rl/data/datasets/__init__.py",
    "nemo_rl/data/datasets/eval_datasets/__init__.py",
    "nemo_rl/data/datasets/eval_datasets/aime.py",
    "nemo_rl/data/datasets/eval_datasets/gpqa.py",
    "nemo_rl/data/datasets/eval_datasets/local_math_dataset.py",
    "nemo_rl/data/datasets/eval_datasets/math.py",
    "nemo_rl/data/datasets/eval_datasets/mmlu.py",
    "nemo_rl/data/datasets/eval_datasets/mmlu_pro.py",
    "nemo_rl/data/datasets/preference_datasets/__init__.py",
    "nemo_rl/data/datasets/preference_datasets/binary_preference_dataset.py",
    "nemo_rl/data/datasets/preference_datasets/helpsteer3.py",
    "nemo_rl/data/datasets/preference_datasets/preference_dataset.py",
    "nemo_rl/data/datasets/preference_datasets/tulu3.py",
    "nemo_rl/data/datasets/processed_dataset.py",
    "nemo_rl/data/datasets/response_datasets/__init__.py",
    "nemo_rl/data/datasets/response_datasets/clevr.py",
    "nemo_rl/data/datasets/response_datasets/deepscaler.py",
    "nemo_rl/data/datasets/response_datasets/geometry3k.py",
    "nemo_rl/data/datasets/response_datasets/oai_format_dataset.py",
    "nemo_rl/data/datasets/response_datasets/oasst.py",
    "nemo_rl/data/datasets/response_datasets/openmathinstruct2.py",
    "nemo_rl/data/datasets/response_datasets/refcoco.py",
    "nemo_rl/data/datasets/response_datasets/response_dataset.py",
    "nemo_rl/data/datasets/response_datasets/squad.py",
    "nemo_rl/data/datasets/utils.py",
    "nemo_rl/data/interfaces.py",
    "nemo_rl/data/multimodal_utils.py",
    "nemo_rl/data/packing/__init__.py",
    "nemo_rl/data/processors.py",
    "nemo_rl/distributed/__init__.py",
    "nemo_rl/distributed/collectives.py",
    "nemo_rl/distributed/named_sharding.py",
    "nemo_rl/distributed/ray_actor_environment_registry.py",
    "nemo_rl/distributed/virtual_cluster.py",
    "nemo_rl/distributed/worker_group_utils.py",
    "nemo_rl/environments/__init__.py",
    "nemo_rl/environments/games/sliding_puzzle.py",
    "nemo_rl/environments/interfaces.py",
    "nemo_rl/environments/math_environment.py",
    "nemo_rl/environments/metrics.py",
    "nemo_rl/environments/rewards.py",
    "nemo_rl/environments/utils.py",
    "nemo_rl/environments/vlm_environment.py",
    "nemo_rl/evals/__init__.py",
    "nemo_rl/evals/answer_parsing.py",
    "nemo_rl/experience/__init__.py",
    "nemo_rl/experience/rollouts.py",
    "nemo_rl/models/__init__.py",
    "nemo_rl/models/dtensor/__init__.py",
    "nemo_rl/models/dtensor/parallelize.py",
    "nemo_rl/models/generation/__init__.py",
    "nemo_rl/models/generation/interfaces.py",
    "nemo_rl/models/generation/vllm/__init__.py",
    "nemo_rl/models/generation/vllm/config.py",
    "nemo_rl/models/generation/vllm/utils.py",
    "nemo_rl/models/generation/vllm/vllm_backend.py",
    "nemo_rl/models/huggingface/__init__.py",
    "nemo_rl/models/megatron/__init__.py",
    "nemo_rl/models/megatron/community_import.py",
    "nemo_rl/models/policy/__init__.py",
    "nemo_rl/models/policy/interfaces.py",
    "nemo_rl/models/policy/utils.py",
    "nemo_rl/utils/__init__.py",
    "nemo_rl/utils/checkpoint.py",
    "nemo_rl/utils/config.py",
    "nemo_rl/utils/native_checkpoint.py",
    "nemo_rl/utils/automodel_checkpoint.py",
    "nemo_rl/utils/nsys.py",
    "nemo_rl/utils/nvml.py",
    "nemo_rl/utils/packed_tensor.py",
    "nemo_rl/utils/prefetch_venvs.py",
    "nemo_rl/utils/timer.py",
    "nemo_rl/utils/venvs.py",
    "tools/model_diagnostics/1.max_model_len_respected.py",
    "tools/model_diagnostics/2.long_generation_decode_vs_prefill.py",
    "tools/model_diagnostics/4.vllm_precision_compilation_test.py",
]

# Disable TypedDict mutation errors since TypedDict objects are regular dicts at runtime
[errors]
missing-attribute = false
